#! /bin/sh

wmname LG3D &
vmware-user-suid-wrapper &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0		# Ancho del borde de ventanas
bspc config window_gap           5		# Espacio Entre Ventanas
bspc config split_ratio          0.52	# Ratio de divicion de Ventanas
bspc config borderless_monocle   true	# Sin Bordes en modo monocle
bspc config gapless_monocle      true	# Sin gaps en modo  monocle

# --- Window Rules ---
#Reglas especificas por ventana

bspc rule -a Caja state=floating follow=on                  # Gestor de archivos flotante
bspc rule -a Gimp desktop='^8' state=floating follow=on		# Gimp en el escritorio 8
bspc rule -a Chromium desktop='^2'							# Cronium en el escritorio 2
bspc rule -a mplayer2 state=floating						# Mplayer Flotante
bspc rule -a Kupfer.py focus=on								# Auto-focus para Kupfer
bspc rule -a Screenkey manage=off							# No administrar Screenkey
bspc rule -a mpv state=floating
bspc rule -a XTerm: state=floating							# XTerm como ventana flotante

# RESOLUCION ARANDR


# WALLPAPER
~/.config/bspwm/wallpaper.sh

# POLYBAR
~/.config/polybar/launch.sh

# BLUETOOTH
blueman-manager --detached &

# CUSTOM
bspc config focus_follows_pointer true

# PICOM
picom &
bspc config border_width 0

xsetroot -cursor_name left_ptr &
xautolock -time 10 -locker "~/.config/bspwm/wall-lock.sh" &
