#comprobar que no soy un bot
#ytdl-raw-options=cookies-from-browser=brave
#ytdl-raw-options=cookies-from-browser=firefox
# funcion para cookies
#ytdl-raw-options=cookies=$HOME/.config/mpv/cookies-youtube.txt
#ytdl-raw-options=js-runtime=/home/n2o/.deno/bin/deno
# Limita la reproduccion del video a 720
#ytdl-format=bestvideo[height<=720][fps<=30]+bestaudio/best
# Ajustar al tamaño de la pantalla
autofit-larger=100%x100%
# mantener la pantalla siempre encima
ontop=yes
# Tamaño fijo de ventana 
#autofit=1280x720
# Activa aceleracion por Hardware
hwdec=vaapi
# por si vaapi falla
profile=fast
hwdec=no
# Filtros para cualquier video
vf=scale=w=-2:h=720:force_original_aspect_ratio=decrease
vf-add=fps=30
# Volumen
volume=70
#cache
cache=yes
cache-secs=60
demuxer-max-bytes=150m
# Quitar mensaje de fuentes 
msg-level=fontconfig=no
